# conda:
#     file: docs/environment.yml
# requirements_file: requirements.txt - this option seems to be ignored by RTD
build:
    image: latest

python:
    version: 3.6
    pip_install: true
    use_system_site_packages: true
    extra_requirements:
        - doc

formats: []
